# Database connection
spring.datasource.url=jdbc:postgresql://ep-hidden-butterfly-ay3jzgj3-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VoHp47KLZUJm
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080